services:
  python:
    container_name: python3.11
    tty: true
    build: .
    working_dir: /root
    volumes:
      - ./workdir:/root/workdir
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo

networks:
  default:
    driver: bridge
