services:
  typst:
    container_name: Typst
    tty: true
    build: .
    working_dir: /root
    volumes:
      - ./workdir:/root/documents
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo

networks:
  default:
    driver: bridge
