services:
  latex:
    container_name: LaTeX
    image: latex:latest
    tty: true
    build: .
    working_dir: /root
    volumes:
      - ./workdir:/root/documents
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo

networks:
  default:
    driver: bridge
