services:
  latex:
    container_name: LaTeX
    tty: true
    build: .
    working_dir: /home/latex
    volumes:
      - ./workdir:/home/latex/documents
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo

networks:
  default:
    driver: bridge
